# Main site information
title: Madelyn Potts
description: The personal website and blog of Madelyn Potts! Exploring cybersecurity, technology, and just whatever else is on her mind.
baseurl: ""
url: "http://madelyn.dev"

# Social media links.
social_media_links:
  github: finaris
  linkedin: madet
  bluesky: madelyn.dev

# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
